### ISSUE TITLE
Upgrade for latest 9.1

### ISSUE THREAD

**Issue by xAt0mZ** [Adubbz/Ghidra-Switch-Loader#15]
Latest build isn't working on latest Ghidra release (October 2019 - sha 29d130dfe85da6ec45dfbf68a344506a8fdcc7cfe7f64a3e7ffb210052d1875e)
![2019-11-29_231203](https://user-images.githubusercontent.com/7642331/69891565-b15e6200-12fd-11ea-8119-5c155a0b2c59.png)

**Comment by Adubbz** [comment]
I've uploaded a build that should now work with Ghidra 9.1.
