### ISSUE TITLE
Crashing in Ghidra 9.1.1

### ISSUE THREAD

**Issue by masagrator** [Adubbz/Ghidra-Switch-Loader#16]
It's not compatible with Ghidra 9.1.1

> Import File - Uncaught Exception: java.lang.NoClassDefFoundError: ghidra/app/util/importer/MemoryConflictHandler
> java.lang.NoClassDefFoundError: ghidra/app/util/importer/MemoryConflictHandler
> 	at adubbz.nx.loader.SwitchLoader.loadProgram(SwitchLoader.java:109)
> 	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
> 	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
> 	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
> 	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
> 	at ghidra.util.task.Task.monitoredRun(Task.java:126)
> 	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> ---------------------------------------------------
> Build Date: 2019-Dec-18 1306 EST
> Ghidra Version: 9.1.1
> Java Home: C:\Program Files\Java\jdk-11.0.4
> JVM Version: Oracle Corporation 11.0.4
> OS: Windows 10 10.0 amd64

Tested on Dragon's Dogma 1.0.1 main and Dark Souls 1.0.0 main

**Comment by Adubbz** [comment]
You're trying to use an old version of the loader with Ghidra 9.1+. I've just added a build specifically for 9.1.1 to releases.
