### ISSUE TITLE
Issue exporting modified exefs main files

### ISSUE THREAD

**Issue by Amethyst-szs** [Adubbz/Ghidra-Switch-Loader#18]
Before I go any further, it is worth point out that I am new to both Ghidra and the Switch Loader extension. This might be something wrong with what I am doing and not an issue with the extension itself.

I am having a problem with getting an exefs main file from exporting. When I go to export program in the CodeBrowser, I can export several different file types. I assume I want a binary file to be exported but that gives me a .bin file that is around twice as big as the original exefs main file. What should I be doing for exporting?

**Comment by masagrator** [comment]
Loader is not for exporting, but for ... loading.

You need to make IPS patch with all your changes manually or by editing uncompressed main with hex editor and making diff with f.e. SIPS.

**Comment by Amethyst-szs** [comment]
Alright. I'll start messing with using uncompressed main files from hactool. Since this issue isn't really about Ghidra-Switch-Loader anymore, I'll close it.
