### ISSUE TITLE
About the usage

### ISSUE THREAD

**Issue by zellfy** [Adubbz/Ghidra-Switch-Loader#2]
Set GHIDRA_INSTALL_DIR to your Ghidra install directory. This can be done by:
1.Adding it to your path
2.Running export GHIDRA_INSTALL_DIR=<Absolute path to Ghidra>.
Using -PGHIDRA_INSTALL_DIR=<Absolute path to Ghidra> when running ./gradlew.
3.Run ./gradlew
4.You'll find the output zip file inside /dist
can you explain these and upload some images, thank you.

**Comment by Adubbz** [comment]
As the build process just involves running commands, I don't think adding images would really help much. I have however improved that section a bit to make it clearer.
