### ISSUE TITLE
Upgrade for 9.2.2

### ISSUE THREAD

**Issue by MarioPossamato** [Adubbz/Ghidra-Switch-Loader#20]
The latest build is not working on Ghidra 9.2.2:
![image](https://user-images.githubusercontent.com/51346942/107023811-27b5ea00-6775-11eb-80bc-1a0751bff66d.png)

**Comment by Mika-Westphal** [comment]
I know it is not a new version but you can here download the old ghidra version: https://ghidra-sre.org/releaseNotes_9.2.3.html
