### ISSUE TITLE
"Unexpected Loader exception from Nintendo Switch Binary" when importing a specific binary

### ISSUE THREAD

**Issue by DaQueenJodi** [Adubbz/Ghidra-Switch-Loader#29]
when importing the main executable from `The Binding of Isaac: Afterbirth+`, I get this error in the logs:
![image](https://user-images.githubusercontent.com/83870316/147784184-6e0c5b1a-b34d-4335-86cb-3552453f452e.png)
 
This happens on both the updated and base versions.

I am using the latest build of the plugin with the latest version of Ghidra

**Comment by DaQueenJodi** [comment]
(I should note that the other games I have access to all import fine)

**Comment by masagrator** [comment]
You should check with other tools like hactool if your main is not corrupted.
This is decompression error.

**Comment by Adubbz** [comment]
Historically when this has happened it has usually been as the result of a bad dump produced by something like NXDumpTool. You should dump the raw NCAs and then use hactool/hactoolnet for extraction.

**Comment by DaQueenJodi** [comment]
alright I'll try that, thanks!

**Comment by DaQueenJodi** [comment]
That was absolutely it, it imports fine now
