### ISSUE TITLE
How to recognize NXO file?

### ISSUE THREAD

**Issue by codiwodi** [Adubbz/Ghidra-Switch-Loader#30]
![Yes](https://i.imgur.com/SAVmwOd.png)

I see you have NXO support, but how do I use it?

 I tried renaming 0x00 to KIP1,NSO0 etc. for fun. Obviously didn't work :)

Thanks :)

**Comment by masagrator** [comment]
NXO is a general name for shared sections in NSO and NRO.
There is no NXO file

**Comment by codiwodi** [comment]
Idk, so I have to make it recognize it as a NRO or NSO for it to use the NXO folder to parse data?
What I'm asking is how? Can't select the Nintendo Switch Binary, when loading it. 

I opened it as AARCH64 v8-A already, it has xrefs and everything, but no segments:) so I can already work on it 👍

**Comment by masagrator** [comment]
And what this file even is?

**Comment by codiwodi** [comment]
Doesn't matter :) Don't actually need a loader anyway.. but would still like to know if there's a way to make it work as is :)

**Comment by masagrator** [comment]
> Doesn't matter

Ok. So I don't care.

**Comment by Adubbz** [comment]
MOD0 is not a file format in itself, it is part of a larger file format that contains it. This is an incomplete dump.
