### ISSUE TITLE
Error When Installing

### ISSUE THREAD

**Issue by Brawlballbob19** [Adubbz/Ghidra-Switch-Loader#33]
When I install the extension, it says “extension not compatible”. I’m using Java 17, could this be the problem? Do I have to use 11?

**Comment by GGLinnk** [comment]
What version of Ghidra do you use ? The latest version of this plugin if for ``10.1.1`` only.

If your Ghidra version is higher than ``10.1.1``, you have two options:
- You can build it yourself. It's relatively easy. It the recommended way.
- You can fix that by manually changing ``.zip/SwitchLoader/extension.properties`` version key to your ghidra version.

**Comment by GGLinnk** [comment]
You can find latest release loader for Ghidra 10.1.5 here : #34
