### ISSUE TITLE
NSO header missing from tree/listing

### ISSUE THREAD

**Issue by GGLinnk** [Adubbz/Ghidra-Switch-Loader#38]
I just noticed that when loading an NSO/exefs the loader deletes everything before the "**MOD0**" magik. That means the NSO header.

Is this a desired behavior?
I find this strange. I haven't seen this behavior on other binary formats.

If this is desired. Can I have a little explanation as to why it has to be done this way?

I would have loved to not create an issue about it but discussion is closed.

**Comment by masagrator** [comment]
Yes. NSO header is not loaded to RAM, so it follows official HOS behavior.

**Comment by Adubbz** [comment]
Yes, @masagrator is correct. This behaviour is also intended to be consistent with the equivalent IDA loader, minimising any confusion in transitioning between the two.
