### ISSUE TITLE
Issue when installing

### ISSUE THREAD

**Issue by PoloNX** [Adubbz/Ghidra-Switch-Loader#39]
Hi, I have this issue when installing the extension

Extension version for [SwitchLoader-1.4.0-19ca180-Ghidra_10.2.2.zip] is incompatible with Ghidra.
---------------------------------------------------
Build Date: 2023-May-10 1508 EDT
Ghidra Version: 10.3
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.7.7-hotspot
JVM Version: Eclipse Adoptium 17.0.7
OS: Windows 11 10.0 amd64
Workstation: PC_DE_CHARLI

**Comment by masagrator** [comment]
Because latest release is incompatible with it. You can either compile it yourself or download from here
https://github.com/TSRBerry/Ghidra-Switch-Loader/releases/tag/1.4.0

**Comment by PoloNX** [comment]
Thanks, and another question. I'm creating one homebrew on my switch and want to debug it. Ghidra can help me to do it ? Maybe by opening the .elf

**Comment by MaKiPL** [comment]
The ELF is typical -Unix executable/program. It's like an EXE on Windows, therefore it's even more than possible for Ghidra to fully support the file. As it's Switch then it's going to be in AArch64, but you should be fine. For NX however it's not natural to work with ELF files, but if it's work as homebrew then fine

**Comment by PoloNX** [comment]
No, I use one .nro on my switch homebrew. I want to follow this guide to debug a crash on my app https://gist.github.com/jam1garner/c9ba6c0cff150f1a2480d0c18ff05e33
