### ISSUE TITLE
Base Addresses

### ISSUE THREAD

**Issue by CovenEsme** [Adubbz/Ghidra-Switch-Loader#47]
I've been using this project for a couple months now and I haven't been able to figure out where the base address for nso files comes from. Why was `0x7100000000` chosen?

**Comment by masagrator** [comment]
It's just arbitrary address. Better have something high as base address so disassembler won't assume that some integers are addresses.

**Comment by CovenEsme** [comment]
Ah cool, thanks. Makes sense :p
