### ISSUE TITLE
Update to Ghidra 11.0

### ISSUE THREAD

**Issue by StevensND** [Adubbz/Ghidra-Switch-Loader#50]
I can't update to Ghidra 11.0

I'm having issues with Gradle.

Could you fix it?.

**Comment by TSRBerry** [comment]
It would have been nice to have the gradle errors in the description as well.
This way I could have known in advance what needs to be changed.

**Comment by StevensND** [comment]
> It would have been nice to have the gradle errors in the description as well. That way I could have known in advance what needs to be changed.

[Errors](https://imgur.com/a/oinkC54l)

Deprecated Gradle features and when I changed it to a newer version I got the line 64 error.

**Comment by StevensND** [comment]
By reinverting the changes and tests I was doing and adding your new changes I was able to fix it. 

[Here is the proof.](https://i.imgur.com/89GepJE.png)

![Captura](https://github.com/Adubbz/Ghidra-Switch-Loader/assets/45856578/31ae99f0-2c64-470f-8065-23fec47d7b3c)

**Comment by TSRBerry** [comment]
You shouldn't get any gradle errors if you are running it using gradlew. Also make sure you are using OpenJDK 17.

**Comment by StevensND** [comment]
> You shouldn't get any gradle errors if you are running it using gradlew. Also make sure you are using OpenJDK 17.

I'm using Github Actions to built it. Anyway on manual build I also had OpenJDK 17 and was having the errors before your changes.

All solved now. Thanks.
