### ISSUE TITLE
Analysis Task: Shared Return Calls - Index 0 out of bounds for lenght 0

### ISSUE THREAD

**Issue by StevensND** [Adubbz/Ghidra-Switch-Loader#52]
Since I update to Ghidra 11 I'm having this problem (which is really annoying) and I don't know what it is due to.... 

[Screenshot](https://i.imgur.com/GfwxoM9.png)

[Screenshot 2](https://i.imgur.com/1LzXuY2.png)

Is it my problem, SwitchLoader's problem? Could you take a look at it?.

Thanks.

Thanks.

![Captura](https://github.com/Adubbz/Ghidra-Switch-Loader/assets/45856578/4f072865-7d32-4151-a10e-212327954293)
![Captura2](https://github.com/Adubbz/Ghidra-Switch-Loader/assets/45856578/1551507d-a592-41f3-b6dc-25777ef58ff4)

**Comment by TSRBerry** [comment]
I don't see any reference to SwitchLoader in the stacktrace. Next time please, copy and paste them into your issue in a code block, that makes it a lot easier to work with them.

It definitely looks odd, could you provide more information? What binary are you analyzing? Which Switch-Loader version are you using? Was this binary analyzed using an older Ghidra version before?

**Comment by StevensND** [comment]
> I don't see any reference to SwitchLoader in the stacktrace. Next time please, copy and paste them into your issue in a code block, that makes it a lot easier to work with them.
> 
> It definitely looks odd, could you provide more information? What binary are you analyzing? Which Switch-Loader version are you using? Was this binary analyzed using an older Ghidra version before?

Right now I'm analyzing another game. I will copy the errors into a .txt and upload it later.

I'm analyzing a main file extracted from a game. Switch-Loader version is the compatible with Ghidra 11.0 (I just merged the changes you did and compile it by myself).

When I used Ghidra 10.4 I didn't have these issues. So could be an issue with Ghidra 11.0?. Could you give me your Switch-Loader 11.0 version compiled to test?. Thanks.

**Comment by StevensND** [comment]
Here's the [pastebin](https://pastebin.com/ZeL0ZvVd) with the errors that I'm getting.

**Comment by TSRBerry** [comment]
What game are you analyzing? Could you use hactool to get the SDK version of the the nca file containing the main nso that you are analyzing?

**Comment by TSRBerry** [comment]
Nevermind, I'm able to reproduce this when I try to analyze the main nso of  "Super Mario Bros. Wonder".
I'll try to figure it out, but I'm currently pretty busy, so it might take some time.

**Comment by TSRBerry** [comment]
This is a Ghidra issue and was fixed just 2 weeks ago: https://github.com/NationalSecurityAgency/ghidra/blob/85d276bce0bb2055c5556825afc810d3163ed15f/Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/lang/protorules/HomogeneousAggregate.java#L71-L74

The current release does not check if the result is empty and tries to access index 0 unconditionally:
```java
if (!DatatypeFilter.extractPrimitives(dt, MAX_PRIMITIVES, null, res)) {
    return false;
}
DataType base = res.get(0);
```

I assume the next release will contain this fix.

**Comment by StevensND** [comment]
> What game are you analyzing? Could you use hactool to get the SDK version of the the nca file containing the main nso that you are analyzing?

It happens with all games that I analyzed using Ghidra 11.

So it seems to be a Ghidra 11 issue then?.

Then I guess I have to stay at 10.4 for now.

**Comment by StevensND** [comment]
Between yesterday and today Ghidra 11.0.1 was released.

I'm testing and so far during my first test the error has disappeared. I will continue testing.

**Comment by TSRBerry** [comment]
The fix for this is definitely part of the new release. Search for `GP-4169` here: https://htmlpreview.github.io/?https://github.com/NationalSecurityAgency/ghidra/blob/Ghidra_11.0.1_build/Ghidra/Configurations/Public_Release/src/global/docs/ChangeHistory.html

**Comment by TSRBerry** [comment]
I also retested it with the updated version and don't encounter the exceptions anymore.

And I just realized you weren't even saying that you are still getting exceptions.. :sweat_smile: 
Imo this issue can be closed now!

**Comment by MediaMoots** [comment]
@TSRBerry Is the latest release compatible with 11.0.1?

**Comment by MediaMoots** [comment]
Nvm, i found the latest here https://github.com/StevensND/Ghidra-Switch-Loader/releases/tag/11.0.1
