### ISSUE TITLE
Gradle Update

### ISSUE THREAD

**Issue by StevensND** [Adubbz/Ghidra-Switch-Loader#58]
![image](https://github.com/user-attachments/assets/383f316f-e13e-436c-ab4c-a55242b0ae55)

I was trying to update SwitchLoader to latest Ghidra version: 11.2

I'm getting this error about Gradle. I saw that you're using 7.5.1 and the latest Gradle version is 8.10.2

Can you update this?. Thanks.

**Comment by StevensND** [comment]
Any news?

**Comment by StevensND** [comment]
Managed to solve the Gradle version error but now I'm getting this error ...

![image](https://github.com/user-attachments/assets/01196a19-f601-4000-bcf3-a464cd470d6d)

**Comment by TSRBerry** [comment]
I'm still on Ghidra 11.0.3. Once the Arch repositories update to Ghidra 11.2 I'll have a look.

**Comment by borntohonk** [comment]
@StevensND latest gradle requirements is JDK 21

this line is no longer permitted in the context, and must be removed https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/build.gradle#L64

after addressing this, then a new issue appears

https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/src/main/java/adubbz/nx/loader/nso0/NSO0Adapter.java#L18-L19

[net.jpountz.lz4](https://mvnrepository.com/artifact/net.jpountz.lz4/lz4) is deprecated, and has been moved to [org.lz4/lz4-java](https://mvnrepository.com/artifact/org.lz4/lz4-java)

**Comment by borntohonk** [comment]
[SwitchLoader-1.6.0-6c208c5-Ghidra_11.2.zip](https://github.com/user-attachments/files/17355142/SwitchLoader-1.6.0-6c208c5-Ghidra_11.2.zip)

**Comment by StevensND** [comment]
> @StevensND latest gradle requirements is JDK 21
> 
> this line is no longer permitted in the context("configuration" cannot be dependency anymore), and must be removed https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/build.gradle#L64
> 
> https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/gradle/wrapper/gradle-wrapper.properties#L3 swap for `distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-bin.zip`
> 
> after addressing this, then a new issue appears
> 
> https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/src/main/java/adubbz/nx/loader/nso0/NSO0Adapter.java#L18-L19
> 
> in other words.
> 
> remove https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/build.gradle#L63-L64
> 
> add implementation group: 'org.lz4', name: 'lz4-java', version: '1.8.0' localDeps group: 'org.lz4', name: 'lz4-java', version: '1.8.0'
> 
> remove https://github.com/Adubbz/Ghidra-Switch-Loader/blob/master/gradle/wrapper/gradle-wrapper.properties#L3
> 
> add distributionUrl=https://services.gradle.org/distributions/gradle-8.10.2-bin.zip

Cool. TYSM for the help!!. 

I was only missing:

add
implementation group: 'org.lz4', name: 'lz4-java', version: '1.8.0'
localDeps group: 'org.lz4', name: 'lz4-java', version: '1.8.0'

Because I had no idea that I needed to modify that. Again: Tysm ♥
